### ISSUE TITLE
Dapper always returning false in case of fetching bit datatype from SQL SERVER 2014 database

### ISSUE THREAD

**Issue by santoshpatro** [DapperLib/Dapper#1661] opened 2021-05-07 18:28 UTC
Hi Team,

Need help on this issue : https://stackoverflow.com/questions/67438988/dapper-always-returning-false-in-case-of-fetching-bit-datatype-from-sql-server-2

Any help on this request is much appreciated

Thanks,
Santosh

**Comment by mgravell** [comment] 2021-05-07 19:47
Bit should map fine. This is usually caused by a column typo. For example,
`IsTestPublishedAndOnboarded` isn't in the SQL. Can you double check the
column names and property names match?

**Comment by santoshpatro** [comment] 2021-05-07 20:10
Thanks @MarcGravell for your response .I have updated the question now. I revalidated it and found still IsTestPublishedAndOnboarded is returned as false which should not be the case. There is also another field IsPublished which is also having the same issue

**Comment by NickCraver** [comment] 2021-05-08 12:02
The updated question helped - the issue is different than thought here: mostly column ordering - I added an answer to explain this better over at https://stackoverflow.com/a/67447310/13249 - hope that helps!

**Comment by NickCraver** [comment] 2021-05-08 16:59
Closing this out since answered above :)

**Closed by NickCraver** 2021-05-08 16:59 UTC

**Comment by mgravell** [comment] 2021-05-08 17:24
Great analysis, thanks Nick

**Comment by santoshpatro** [comment] 2021-05-08 19:06
Thanks much Nick and @mgravell  for your help. It worked me for now :)
