### ISSUE TITLE
 FatalExecutionEngineError when using splitOn and structs.

### ISSUE THREAD

**Issue by AxelMarquez** [DapperLib/Dapper#606] opened 2016-09-09 19:21 UTC
Hi!

SplitOn and structs seem to not play well together, for example: 

```
var dogs = _db.Query<Dog, Cat, Dog>("SELECT 'Lucky' AS Name, 2 AS Age, 3 AS Weight", (dog, cat) => { dog.Friend = cat; return dog; }, splitOn: "Age");
```

```
public class Dog
{
    public string Name { get; set; }
    public Cat Friend { get; set; }
}
```

```
public struct Cat
{
    public int Age { get; set; }
    public int Weight { get; set; }
}
```

Produces `FatalExecutionEngineError`, however if I change Cat to a class it works as expected.
I'm using version 1.50.2

Thanks!!!
(btw, awesome library)

**Comment by chilversc** [comment] 2016-09-21 12:29
It seems like this isn't supported at the moment.

I've located the cause of the error, https://github.com/StackExchange/dapper-dot-net/blob/6e03f898003bd1d7c1d5c30546ba8174cb191f8c/Dapper/SqlMapper.cs#L3167

```csharp
if (first && returnNullIfFirstMissing)
{
    il.Emit(OpCodes.Pop);
    il.Emit(OpCodes.Ldnull); // stack is now [null]
    il.Emit(OpCodes.Stloc_1);
    il.Emit(OpCodes.Br, allDone);
}
```

If type is a value type then the `ldnull` instruction in invalid as the storage slot can't hold a null value.

To support this there are 2 cases that need to be handled, if the return type is a nullable struct and if the return type is a non-nullable struct (e.g. `Query<Dog, Cat, Dog>` vs `Query<Dog, Cat?, Dog>`).

**Comment by chilversc** [comment] 2016-09-21 12:53
Change that, there's only 1 case, the non-nullable case since `Query` doesn't support nullable structs so cat is always null for `Query<Dog, Cat?, Dog>`.

So the main question is, should a struct follow the same rules as an object and stop mapping if the first field is null, yielding a default value for the struct; or since the struct cannot be null should it continue to map all the fields?

Stopping mapping when the first field is null would maintain parity with reference types and allows introducting support for nullable value types later without introducting a breaking change.

Continuing to map would be in the spirt of value objects though. Nullable structs could still be supported, but there would be divergent behaviour. When the first column is null then reference types and nullable value types would stop mapping and yield null while non-nullable value types would continue mapping.

Personally I'd choose to stop if the first value is null to maintain parity with reference types. Support to continue mapping could be added later if the same support is added for reference types (#266).

## Stop if first column is null

```csharp
if (first && returnNullIfFirstMissing)
{
    if (type.IsValueType())
    {
        il.Emit(OpCodes.Pop);
        il.Emit(OpCodes.Br, allDone);
    }
    else
    {
        il.Emit(OpCodes.Pop);
        il.Emit(OpCodes.Ldnull); // stack is now [null]
        il.Emit(OpCodes.Stloc_1);
        il.Emit(OpCodes.Br, allDone);
    }
}
```

## Continue mapping if first field is null

```csharp
if (first && returnNullIfFirstMissing && !type.IsValueType())
{
    il.Emit(OpCodes.Pop);
    il.Emit(OpCodes.Ldnull); // stack is now [null]
    il.Emit(OpCodes.Stloc_1);
    il.Emit(OpCodes.Br, allDone);
}
```

**Comment by NickCraver** [comment] 2016-11-08 12:01
@mgravell thoughts? Not sure what a fix for this would break

**Comment by NickCraver** [comment] 2021-05-09 00:21
Collapsing into #773 which has a bit more info

**Closed by NickCraver** 2021-05-09 00:21 UTC
