### ISSUE TITLE
Object reference not set to an instance of an object. at Dapper.SqlMapper.QueryImpl[T]

### ISSUE THREAD

**Issue by doggy8088** [DapperLib/Dapper#1576] opened 2020-11-20 16:11 UTC
I'm using Dapper `v1.50.4`. There is a exception occurred by unknown reason. The exception log is below:

```log
System.NullReferenceException: Object reference not set to an instance of an object. 
at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1103 
at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable) 
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723 
...
```

I've been checked with this line from the Dapper source code with `v1.50.4` tag here:
https://github.com/StackExchange/Dapper/blob/1.50.4/Dapper/SqlMapper.cs#L1103

In my code, The generic type is `int?` for this query. The SQL I executed can only return `int` or `null`. I couldn't figure it out why exception throw. Is there any possibility could produce this weird exception from [this line](https://github.com/StackExchange/Dapper/blob/1.50.4/Dapper/SqlMapper.cs#L1103)?

**Comment by mgravell** [comment] 2020-11-20 20:01
What would we need to repro this? Do you have something that demonstrates
your query code, and ideally the number / composition of rows/ columns? It
is much easier to investigate from a repro.

**Comment by NickCraver** [comment] 2021-05-08 16:59
Can't reproduce this without more info (`.Query<int?>` does work) - something subtle is happening here and we'd need a repro. Going to close this out unless we can get some more info, then happy to re-open!

**Closed by NickCraver** 2021-05-08 16:59 UTC
