### ISSUE TITLE
Error Max Pool Size 

### ISSUE THREAD

**Issue by richardandrade** [DapperLib/Dapper#1837] opened 2022-10-13 14:34 UTC
From time to time an exceptional exception at the time of opening the connection with the DB.

   "Timeout elapsed before getting a connection from the pool. This could be because all connections in the pool were in use and the maximum pool size was reached."

I did a quick analysis and found this code block from https://github.com/DapperLib/Dapper/blob/main/Dapper/SqlMapper.cs.

Look at the finally and look for the wasClosed variable, it looks like this:

  if (wasClosed) cnn.Close();

Shouldn't it be like this?

  if (!wasClosed) cnn.Close();

Original Code:
```
private static IEnumerable<T> QueryImpl<T>(this IDbConnection cnn, CommandDefinition command, Type effectiveType)
        {
            object param = command.Parameters;
            var identity = new Identity(command.CommandText, command.CommandType, cnn, effectiveType, param?.GetType());
            var info = GetCacheInfo(identity, param, command.AddToCache);

            IDbCommand cmd = null;
            IDataReader reader = null;

            bool wasClosed = cnn.State == ConnectionState.Closed;
            try
            {
                cmd = command.SetupCommand(cnn, info.ParamReader);

                if (wasClosed) cnn.Open();
                reader = ExecuteReaderWithFlagsFallback(cmd, wasClosed, CommandBehavior.SequentialAccess | CommandBehavior.SingleResult);
                wasClosed = false; // *if* the connection was closed and we got this far, then we now have a reader
                // with the CloseConnection flag, so the reader will deal with the connection; we
                // still need something in the "finally" to ensure that broken SQL still results
                // in the connection closing itself
                var tuple = info.Deserializer;
                int hash = GetColumnHash(reader);
                if (tuple.Func == null || tuple.Hash != hash)
                {
                    if (reader.FieldCount == 0) //https://code.google.com/p/dapper-dot-net/issues/detail?id=57
                        yield break;
                    tuple = info.Deserializer = new DeserializerState(hash, GetDeserializer(effectiveType, reader, 0, -1, false));
                    if (command.AddToCache) SetQueryCache(identity, info);
                }

                var func = tuple.Func;
                var convertToType = Nullable.GetUnderlyingType(effectiveType) ?? effectiveType;
                while (reader.Read())
                {
                    object val = func(reader);
                    yield return GetValue<T>(reader, effectiveType, val);
                }
                while (reader.NextResult()) { /* ignore subsequent result sets */ }
                // happy path; close the reader cleanly - no
                // need for "Cancel" etc
                reader.Dispose();
                reader = null;

                command.OnCompleted();
            }
            finally
            {
                if (reader != null)
                {
                    if (!reader.IsClosed)
                    {
                        try { cmd.Cancel(); }
                        catch { /* don't spoil the existing exception */ }
                    }
                    reader.Dispose();
                }
                if (wasClosed) cnn.Close();
                
                cmd?.Parameters.Clear();
                cmd?.Dispose();
            }
        }
```

**Comment by mgravell** [comment] 2022-10-13 14:36
No, it is correct as written. The intent is to leave the connection in the same state in which it was found. If the connection was open on the way in: leave it alone - it could be in a transaction, or using temp tables, etc; if it was closed on the way in, that means *we opened it*, so: we should close it on the way out.

**Comment by richardandrade** [comment] 2022-10-13 14:44
> 

Okay, but we don't use the same connection, we're always using a new connection, shouldn't it be closing?

**Comment by mgravell** [comment] 2022-10-13 14:53
Without seeing your connection code, I can't possibly comment on that; for example, if your code looks like this:

``` c#
var conn = new SomeConnectionType(connectionString);
conn.Open();
conn.ExecuteWhatever();
```

then your code may have connection problems, but the problem isn't Dapper - the problem is the missing `using`:

``` c#
using var conn = new SomeConnectionType(connectionString); // fixed it!
// no change here
```

**Comment by richardandrade** [comment] 2022-10-13 15:11
> 

We solved by putting the using, I thought that dapper could close the connection for it, maybe if the dapper put some option that could indicate this, it would be interesting. But here's the code block we make:

```
    public static IEnumerable<T> Query<T>(string query, object param = null, int? commandTimeout = DefaultTimeOut, string connString = null) =>
      db(connString: connString).Query<T>(query, param, commandType: CommandType.Text, commandTimeout: commandTimeout);

    internal static DbConnection db(string domain = null, string connString = null) => Database.GetConnection(domain, connString);

internal static DbConnection GetConnection(string domain = null, string connectionString = null)
    {
      if (string.IsNullOrEmpty(connectionString))
      {
        var identity = Thread.CurrentPrincipal == null ? new DirectorIdentity(0, null) : (DirectorIdentity)Thread.CurrentPrincipal.Identity;
        connectionString = string.IsNullOrEmpty(domain)
          ? Settings.ConnectionString(identity?.Domain)
          : Settings.ConnectionString(domain);
      }

      DbConnection conexao;

      var partes = DesmontarConnectionString(connectionString);
      switch (partes[0].ToLower())
      {
        case "sql":
        case "mssql":
          conexao = new SqlConnection(partes[1]);
          break;
        case "pg":
        case "postgres":
          conexao = new NpgsqlConnection(partes[1]);
          break;
        case "mysql":
          conexao = new MySqlConnection(partes[1]);
          break;
        default:
          conexao = null;
          break;
      }

      conexao?.Open();
      return conexao;
    }
```

**Comment by mgravell** [comment] 2022-10-13 16:10
If you *don't* open the connection: Dapper will do most of what you want here, i.e. it will at least `Close()` the connection for you. It wouldn't be *disposed*, but the important part of dispose is the close, so... maybe close enough.

Suggestion: you could add an optional `bool openConnection = true` parameter on your `GetConnection` (that controls whether the `conexao?.Open();` line runs), and explicitly pass `false` in this case.

**Comment by mgravell** [comment] 2022-10-13 16:14
Importantly, what you *can't* do is add `using` blindly here, especially for "open" queries (`buffered: false`), for example:

``` c#
 public static IEnumerable<T> QueryNonBuffered<T>(string query, object param = null, int? commandTimeout = DefaultTimeOut, string connString = null)
{
    using var conn = db(connString: connString);
    return conn.Query<T>(query, param, commandType: CommandType.Text, commandTimeout: commandTimeout, buffered: false);
}
```

The problem here is that the `using` will kill the connection as soon as the method exits, which is *before* the data has been iterated (because of the `buffered: false`). Ditto if using the `GridReader` or `IDataReader` API. You'll usually get away with it if you're just using `Query<T>` with the default (buffered) behaviour, or `Execute` etc.

**Closed** 2022-10-13 19:39 UTC
