### ISSUE TITLE
Connection disposed

### ISSUE THREAD

**Issue by franksorro** [DapperLib/Dapper#2036] opened 2024-01-30 09:48 UTC
Using Dapper version 2.1.28 with MySQL.Data 8.3.0, after first query execution, the database connection is set to disposed

**Comment by kbilsted** [comment] 2024-02-17 11:01
Full example please, @franksorro

**Comment by mgravell** [comment] 2024-02-17 11:15
This seems ... unlikely; happy to take a look if there's a repro, but: Dapper has been used extensively, and randomly killing connections: would have been noticed. It doesn't do anything different for MySql connections vs anything else.

**Comment by JonathanMagnan** [comment] 2024-02-22 17:07
Hello @franksorro ,

I added an article on the learndapper website that could explain your issue: [The connection had been disposed](https://www.learndapper.com/troubleshooting/the-connection-had-been-disposed)

I tested the code with MySQL.Data 8.3.0 and I successfully reproduced the same exact error.

Let me know if that was the cause of the issue.

If you believe your issue is something else, could you provide a code example that throws the issue? So I could update the article.

---

**Disclaimer**: To avoid confusion, I'm a simple contributor to Dapper. However, I own the [Learn Dapper](https://www.learndapper.com/) and [Dapper Plus](https://dapper-plus.net/).

**Comment by mgravell** [comment] 2024-02-22 18:00
These ^^^ examples where some operation escapes the scope of the connection is indeed the usual cause of such errors; this isn't specific to Dapper - the exact same thing would happen if the source was, for example, a `Socket`, a `FileStream`, a gRPC proxy, or anything else. Just to add one more Dapper-specific scenario - another way you could cause this would be with non-buffered data; consider:

``` c#
IEnumerable<Foo> GetFoos()
{
    using var conn = CreateOpenConnection();
    return conn.Query<Foo>(SQL, args, buffered: false);
}
...
foreach (var row in GetFoos())
{
    Write(row.Whatever);
}
```

with the above non-buffered usage, the sequence we're iterating is sat on a connection that is disposed before it is ever invoked, so: failure. This is just one more way of the same scenario: we've caused an operation to escape the lifetime of a dependent object (@JonathanMagnan I wonder if the non-buffered example might be useful there)

---

IMO: we would need a specific code example to actually offer more concrete advice, but I *strongly suspect* that the cause is indeed: one of these cases. I'm going to close the issue, as non-answerable, but: I invite you (@franksorro) to provide an example if it is still causing problems - happy to reopen, but it would need code to look at.

**Closed by mgravell** 2024-02-22 18:00 UTC

**Comment by bgrainger** [comment] 2024-02-22 18:32
Note that MySql.Data only implemented the "Async" methods very recently (in v8.0.33); before that, they all [ran synchronously](https://bugs.mysql.com/bug.php?id=70111). So code that was "working" with MySql.Data 8.0.32 and earlier could start throwing exceptions when using the latest versions of MySql.Data because the `Task` returned from `ExecuteReaderAsync` is no longer completed and the `MySqlConnection` it's using needs to be kept alive (and undisposed) until the result set is read.

**Comment by mgravell** [comment] 2024-02-22 18:36
yup, if they've moved from async-over-sync to true async, then indeed a **faulty** line such as:

``` c#
Task<Customer> GetCustomerAsync(int id)
{
    using var conn = CreateConnection();
    return conn.QuerySingleAsync(sql, new { id });
}
```

will work differently - with async-over-sync, this will work by happy accident (despite being invalid); however, the *correct* version is:

``` c#
async Task<Customer> GetCustomerAsync(int id)
{
    using var conn = CreateConnection();
    return await conn.QuerySingleAsync(sql, new { id });
}
```

which will work for both async-over-sync and true async in the underlying ADO.NET provider. The important difference is that the `await` extends the lifetime of `conn` until after the operation has completed, which now might be "not yet".

**Comment by JonathanMagnan** [comment] 2024-02-23 17:38
Thank you @mgravell , I added the [non-buffered query issue](https://www.learndapper.com/troubleshooting/the-connection-had-been-disposed#non-buffered-query-issue) to the article, I didn't think about this case. I also added the example of using the QueryUnbufferedAsync method. Finally, I added in the conclusion section that those issues are not related to Dapper but a bad connection usage.

Oh wow, thank @bgrainger for this info. I was wondering yesterday, when creating the article, why I started to get the bug only when I upgraded to the latest version. I also added your information in the conclusion section.
